### ISSUE TITLE
Não pode mais ser instalado no PfSense 2.4.3 (impossível instalar os pacotes de dependência)

### ISSUE THREAD

**Issue by bbicudo** [pf2ad/pf2ad#3]
A versão 2.4.3 está travada para a instalação de pacotes. Agora ele só permite a instalação do squid/squidguard se atualizado para versão 2.4.4 e o pf2ad não permite a instalação nessa versão. Existe alguma edição que possa ser realizada no arquivo para que o mesmo permita a instalação do patch do samba4 na versão nova do PFSense?

**Comment by eakarasev** [comment]
Hi, I changed the release number in /etc/release from 2.4.4 to 2.4.3. It worked

**Comment by bbicudo** [comment]
> Hi, I changed the release number in /etc/release from 2.4.4 to 2.4.3. It worked

Can't find "/release" under /etc

Where did you change it?

**Comment by cassianorl** [comment]
look at the file /etc/version

**Comment by bbicudo** [comment]
@cassianorl @eakarasev 

You're both my heroes <3 

It worked! PERFECT!

THANKS!!!!!
